name: C/C++ CI

on:
  push:
    branches: "main"

jobs:
  build:

    runs-on: ubuntu_latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    - name: All Upload
      uses: actions/upload-artifact@v4
      with:
        name: TJAP_3DS_${}
        path: ./
